# Generated by Django 5.0.1 on 2024-03-15 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='occasion_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.occasion'),
        ),
    ]
